### PR TITLE
[FIX] PWA에서 서비스 워커가 실행되지 않는 문제 해결

### LINKED ISSUE #243: [FIX] PWA에서 service worker가 실행되지 않는 문제 해결
## Description 💭
- PWA 환경에서 service worker가 실행되지 않는 문제를 해결한다.

## TODO ✅
- [x] 서비스 워커 파일을 src 폴더로 이동한다.

### PR DESCRIPTION
**Pull request by young-jin-son**
## Issue Number
close #243 
## As-Is

- PWA 환경에서 서비스워커가 실행되지 않음
## To-Be

- [x] 서비스 워커 파일을 public에서 src로 이동

## Check List

- [x] 테스트가 전부 통과되었나요?
- [x] 모든 commit이 push 되었나요?
- [x] merge할 branch를 확인했나요?
- [x] Assignee를 지정했나요?
- [x] Label을 지정했나요?

## (Optional) Additional Description
PWA injectManifest 전략을 사용할 경우 서비스워커를 src 폴더에 두어야 합니다.

https://vite-pwa-org.netlify.app/guide/inject-manifest

## Summary by CodeRabbit

- **New Features**
  - Introduced Firebase messaging capabilities for enhanced communication functionalities.
  - Improved service worker lifecycle management, allowing for immediate activation and better client control.
  - Added a new URL for accessing the FCM token endpoint.

- **Chores**
  - Streamlined progressive web app configurations to optimize resource handling and overall app performance.
  - Updated service worker registration to use an absolute path for improved reliability.
  - Added a new dependency for Firebase to support messaging features.
  - Enhanced GitHub Actions workflow with additional environment variable assignments for Firebase configuration.
  - Updated notification subscription process to utilize device tokens instead of push subscriptions.
  - Adjusted ESLint rules for better development experience.
  - Modified styles for the `HorizontalLine` component to improve layout spacing.
  - Removed the unused `HorizontalLine` component from the `PlanInfoHeader` styling.

### CODE REVIEW

File: frontend/src/service-worker.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
+
+importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.5.4/workbox-sw.js');
```
Comment (rbgksqkr) [inline frontend/src/service-worker.js:2]: # 💭 질문 💭

FCM에서도 이 파일도 쓰는건가요??

**Review by rbgksqkr — APPROVED** [review]
고생 많았습니다,,,,,FCM + PWA로는 IOS에서도 진짜 잘오네요 결국 해낸 🔥🔥🔥
